version: '3.8'
services:
  web:
    build: .
    ports:
      - "80:5001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://0.0.0.0:5001
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=postgres;User Id=arinakataeva;Password=arinka785;
    depends_on:
      - db

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: arinakataeva
      POSTGRES_PASSWORD: arinka785
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
